/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    certifications: Certification;
    industries: Industry;
    'blog-posts': BlogPost;
    clients: Client;
    faqs: Faq;
    services: Service;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'company-info': CompanyInfo;
    'site-images': SiteImage;
  };
  globalsSelect: {
    'company-info': CompanyInfoSelect<false> | CompanyInfoSelect<true>;
    'site-images': SiteImagesSelect<false> | SiteImagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  /**
   * Stock Keeping Unit (e.g. VCP-IND-0001)
   */
  sku?: string | null;
  /**
   * Chemical formula, e.g. Na₂SO₄
   */
  formula?: string | null;
  /**
   * CAS Registry Number
   */
  cas?: string | null;
  status: 'active' | 'inactive' | 'discontinued';
  category: 'industrial' | 'specialty' | 'pharmaceutical';
  /**
   * e.g. Surfactants, Solvents, Anti-fungal APIs
   */
  subcategory?: string | null;
  /**
   * Searchable tags for filtering
   */
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  description: string;
  /**
   * Primary supplier or manufacturer name
   */
  supplier?: string | null;
  /**
   * Country of origin (e.g. India, China, Germany)
   */
  originCountry?: string | null;
  /**
   * Base price (0 or blank = price on request)
   */
  price?: number | null;
  /**
   * ISO 4217 currency code
   */
  currency?: string | null;
  /**
   * Price per unit, e.g. /kg, /MT, /drum
   */
  priceUnit?: string | null;
  /**
   * Base UOM: kg, L, MT, etc.
   */
  unitOfMeasure?: string | null;
  /**
   * Net weight per unit, e.g. 25 kg
   */
  weight?: string | null;
  /**
   * Package dimensions, e.g. 60×40×30 cm
   */
  dimensions?: string | null;
  /**
   * GHS / UN hazard class, e.g. Class 8 Corrosive
   */
  safetyClass?: string | null;
  applications?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  industries?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  grades?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  packaging?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Technical specifications as key-value pairs
   */
  specs?:
    | {
        /**
         * e.g. Purity, Moisture, pH
         */
        key: string;
        /**
         * e.g. ≥ 99.0%
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Google Drive share URL for the primary product image.
   */
  imageUrl?: string | null;
  /**
   * Additional product images (Google Drive URLs)
   */
  images?:
    | {
        /**
         * Google Drive share URL
         */
        url: string;
        /**
         * Image caption / alt text
         */
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Regulatory & compliance documents (COA, TDS, MSDS, SDS)
   */
  documents?:
    | {
        docType: 'COA' | 'TDS' | 'MSDS' | 'SDS' | 'SPEC' | 'OTHER';
        /**
         * Google Drive share URL for the document
         */
        fileUrl: string;
        /**
         * Display name for the document
         */
        fileName?: string | null;
        /**
         * Who uploaded this document
         */
        uploadedBy?: string | null;
        accessLevel?: ('public' | 'on-request' | 'internal') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  /**
   * e.g. ISO 9001:2015
   */
  name: string;
  slug: string;
  /**
   * e.g. ISO 9001
   */
  shortName: string;
  /**
   * e.g. Quality Management System
   */
  description: string;
  /**
   * Certifying body, e.g. Bureau Veritas
   */
  body: string;
  scope: string;
  /**
   * e.g. Manufacturing & Supply
   */
  scopeType: string;
  keyAreas?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Google Drive share URL for the certification badge/image
   */
  imageUrl?: string | null;
  /**
   * e.g. 2027 or Ongoing
   */
  validUntil: string;
  importance: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  name: string;
  slug: string;
  description: string;
  longDescription: string;
  /**
   * Lucide icon name, e.g. Pill, Shirt, Paintbrush
   */
  icon: string;
  /**
   * Industry image (upload)
   */
  image?: (number | null) | Media;
  /**
   * Google Drive share URL for industry image (preferred over upload)
   */
  imageUrl?: string | null;
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  challenges?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  solutions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Names of chemicals used in this industry
   */
  chemicalsUsed?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  whyChooseUs: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  category: string;
  date: string;
  thumbnail?: (number | null) | Media;
  /**
   * Google Drive share URL for blog thumbnail (preferred over upload)
   */
  thumbnailUrl?: string | null;
  /**
   * e.g. 5 min read
   */
  readTime: string;
  /**
   * Full blog post content (optional, for future use)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  /**
   * Client logo image (upload)
   */
  logo?: (number | null) | Media;
  /**
   * Google Drive share URL for client logo (preferred over upload)
   */
  logoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description: string;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  formula?: T;
  cas?: T;
  status?: T;
  category?: T;
  subcategory?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  description?: T;
  supplier?: T;
  originCountry?: T;
  price?: T;
  currency?: T;
  priceUnit?: T;
  unitOfMeasure?: T;
  weight?: T;
  dimensions?: T;
  safetyClass?: T;
  applications?:
    | T
    | {
        value?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        value?: T;
        id?: T;
      };
  grades?:
    | T
    | {
        value?: T;
        id?: T;
      };
  packaging?:
    | T
    | {
        value?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  imageUrl?: T;
  images?:
    | T
    | {
        url?: T;
        caption?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        docType?: T;
        fileUrl?: T;
        fileName?: T;
        uploadedBy?: T;
        accessLevel?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortName?: T;
  description?: T;
  body?: T;
  scope?: T;
  scopeType?: T;
  keyAreas?:
    | T
    | {
        value?: T;
        id?: T;
      };
  imageUrl?: T;
  validUntil?: T;
  importance?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  longDescription?: T;
  icon?: T;
  image?: T;
  imageUrl?: T;
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  challenges?:
    | T
    | {
        value?: T;
        id?: T;
      };
  solutions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  chemicalsUsed?:
    | T
    | {
        value?: T;
        id?: T;
      };
  whyChooseUs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  date?: T;
  thumbnail?: T;
  thumbnailUrl?: T;
  readTime?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage company details — name, contact, address, and stats displayed across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info".
 */
export interface CompanyInfo {
  id: number;
  name: string;
  tagline: string;
  location?: string | null;
  founded?: string | null;
  /**
   * e.g. 10+
   */
  experience?: string | null;
  /**
   * e.g. 16+
   */
  productsCount?: string | null;
  /**
   * e.g. 30+
   */
  countriesServed?: string | null;
  /**
   * e.g. 5000+ MT
   */
  monthlyCapacity?: string | null;
  email: string;
  phone: string;
  /**
   * Without + prefix, e.g. 919876543210
   */
  whatsapp: string;
  address?: string | null;
  /**
   * Business hours, e.g. Mon–Sat: 9:00 AM – 6:00 PM IST
   */
  hours?: string | null;
  website?: string | null;
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage all website images using Google Drive share URLs. Paste the Drive share link — the site auto-generates optimized sizes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images".
 */
export interface SiteImage {
  id: number;
  /**
   * Google Drive URL for the hero background image (1920×800 recommended)
   */
  heroBackground?: string | null;
  /**
   * Google Drive URL for the hero overlay/foreground image
   */
  heroOverlay?: string | null;
  /**
   * Main image for the About page (800×600 recommended)
   */
  aboutMain?: string | null;
  /**
   * Factory/facility image for About page
   */
  aboutFactory?: string | null;
  /**
   * Team photo for About page
   */
  aboutTeam?: string | null;
  /**
   * Company logo (Google Drive URL) — used in navbar and footer
   */
  logo?: string | null;
  /**
   * Company name logo / wordmark (Google Drive URL)
   */
  logoName?: string | null;
  /**
   * White/inverted logo for dark backgrounds
   */
  logoWhite?: string | null;
  /**
   * Default product image when a product has no image set
   */
  defaultProduct?: string | null;
  /**
   * Default blog thumbnail when a post has no image set
   */
  defaultBlog?: string | null;
  /**
   * Default certification badge image
   */
  defaultCertification?: string | null;
  /**
   * Default industry image
   */
  defaultIndustry?: string | null;
  /**
   * Background image for CTA / banner sections
   */
  ctaBackground?: string | null;
  /**
   * Banner image for the Export page
   */
  exportBanner?: string | null;
  /**
   * Banner image for the Quality page
   */
  qualityBanner?: string | null;
  /**
   * General image gallery — facility photos, labs, warehouse, etc.
   */
  gallery?:
    | {
        /**
         * Google Drive share URL
         */
        url: string;
        /**
         * Alt text for the image (required for accessibility)
         */
        altText: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info_select".
 */
export interface CompanyInfoSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  location?: T;
  founded?: T;
  experience?: T;
  productsCount?: T;
  countriesServed?: T;
  monthlyCapacity?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  hours?: T;
  website?: T;
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-images_select".
 */
export interface SiteImagesSelect<T extends boolean = true> {
  heroBackground?: T;
  heroOverlay?: T;
  aboutMain?: T;
  aboutFactory?: T;
  aboutTeam?: T;
  logo?: T;
  logoName?: T;
  logoWhite?: T;
  defaultProduct?: T;
  defaultBlog?: T;
  defaultCertification?: T;
  defaultIndustry?: T;
  ctaBackground?: T;
  exportBanner?: T;
  qualityBanner?: T;
  gallery?:
    | T
    | {
        url?: T;
        altText?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}